//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _222_Korygin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Korygin_DB_PaymentEntities : DbContext
    {
        public static Korygin_DB_PaymentEntities _context;
        public Korygin_DB_PaymentEntities()
            : base("name=Korygin_DB_PaymentEntities")
        {
        }

        /// <summary>
        /// Возвращает экземпляр контекста базы данных, используя паттерн Singleton.
        /// </summary>
        /// <returns>Единый экземпляр контекста базы данных.</returns>

        /// <example>
        /// <code>
        /// // Получение контекста базы данных
        /// using (var db = GetContext())
        /// {
        ///     var users = db.Users.ToList();
        /// }
        /// </code>
        /// </example>
        public static Korygin_DB_PaymentEntities GetContext()
        {
            if (_context == null)
            {
                _context = new Korygin_DB_PaymentEntities();
            }
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Category { get; set; }
        public DbSet<Payment> Payment { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<User> User { get; set; }
    }
}
